import type { Metadata } from "next";
import { EditorialPage } from "@/components/editorial-page";

export const metadata: Metadata = { title: "Privacy Policy", description: "Learn what limited information FuseMosaic may process and how privacy-related inquiries are handled.", alternates: { canonical: "/privacy" } };
export default function PrivacyPage() { return <EditorialPage eyebrow="Legal" title="Privacy Policy" copy="FuseMosaic aims to collect as little personal information as reasonably necessary to operate this hobby website.">
  <p><strong>Last updated: September 2026</strong></p>
  <h2>Information You Provide</h2><p>If you contact us by email or through a contact form, we may receive information such as:</p><ul><li>your email address;</li><li>your name, if provided;</li><li>the contents of your message;</li><li>information you voluntarily provide with an intellectual-property complaint or other request.</li></ul><p>We use this information only to respond to your request, operate the website, address abuse or rights complaints, and meet legitimate legal obligations.</p>
  <h2>Automatically Collected Information</h2><p>Like most websites, our hosting, security, analytics, or infrastructure providers may automatically process technical information such as:</p><ul><li>IP address;</li><li>browser and device type;</li><li>approximate geographic region;</li><li>pages visited;</li><li>referral source;</li><li>timestamps;</li><li>security and performance information.</li></ul><p>This information may be used for website security, abuse prevention, performance monitoring, and aggregated traffic analytics.</p>
  <h2>Cookies and Analytics</h2><p>FuseMosaic may use essential cookies or similar technologies required for security and basic functionality.</p><p>If analytics services are used, they may process technical and usage information according to their own privacy practices.</p><p>FuseMosaic does not intentionally sell personal information.</p>
  <h2>Third-Party Services</h2><p>FuseMosaic may rely on infrastructure providers such as hosting, content-delivery, security, analytics, or file-storage services.</p><p>Those providers may process limited technical information as necessary to provide their services.</p>
  <h2>Data Retention</h2><p>We retain personal information only for as long as reasonably necessary for the purpose for which it was collected, including responding to inquiries, handling rights complaints, maintaining security records, and complying with legal obligations.</p>
  <h2>Children</h2><p>FuseMosaic provides general craft content and does not knowingly seek to collect personal information directly from children.</p><p>If you believe a child has submitted personal information to us, please contact us and we will review the request.</p>
  <h2>Your Privacy Requests</h2><p>You may contact us regarding personal information that you have directly provided to FuseMosaic.</p><p><strong>Privacy contact: <a href="mailto:rakezhou@hotmail.com">rakezhou@hotmail.com</a></strong></p><p>Applicable privacy rights may vary depending on where you live.</p>
  <h2>Security</h2><p>We use reasonable technical and organizational measures intended to protect website systems and the limited information we process.</p><p>No internet service can guarantee absolute security.</p>
  <h2>Updates</h2><p>We may update this policy when our practices or services change.</p><p>The current version and update date will always appear on this page.</p>
</EditorialPage>; }
