import { getFuseMosaicEnv } from "@/lib/cloudflare";
import { categories as fallbackCategories, patterns as fallbackPatterns, type ArtVariant, type Category, type Pattern } from "@/data/patterns";

const art: Record<string, ArtVariant> = { animals:"fox", people:"flower", "chinese-style":"phoenix", food:"berry", fruit:"berry", "traditional-culture":"lantern", decorations:"moth", "large-patterns":"dragon", other:"flower" };
type Row = { id:string; slug:string; title:string; description:string; preview_url:string|null; download_url:string|null; grid_width:number|null; grid_height:number|null; colors:string; total_beads:number|null; difficulty:string|null; estimated_size:string|null; featured:number; category_name:string|null; category_slug:string|null; seo_title:string|null; seo_description:string|null; status:string };
function map(row: Row): Pattern { let colors: Pattern["colors"]=[]; try { colors=JSON.parse(row.colors) as Pattern["colors"]; } catch {} return { slug:row.slug,title:row.title,category:row.category_name??"Other",categorySlug:row.category_slug??"other",description:row.description,previewImage:row.preview_url??"",downloadImage:row.download_url??"#",downloadPdf:"#",gridWidth:row.grid_width??0,gridHeight:row.grid_height??0,colors,totalBeads:row.total_beads??0,difficulty:(row.difficulty as Pattern["difficulty"])||"Beginner",estimatedSize:row.estimated_size??"",featured:Boolean(row.featured),status:"published",art:art[row.category_slug??"other"]??"flower" }; }
function database() { return getFuseMosaicEnv().PATTERNS_DB; }
const published = "p.status='published' AND p.rights_status='approved'";
export async function publicPatterns(query?: string) { const db=database(); if(!db) return query ? fallbackPatterns.filter((p)=>`${p.title} ${p.category} ${p.difficulty} ${p.description}`.toLowerCase().includes(query.toLowerCase())) : fallbackPatterns; const search=query?" AND (p.title LIKE ? OR p.description LIKE ? OR c.name LIKE ?)":""; const args=query?[`%${query}%`,`%${query}%`,`%${query}%`]:[]; const result=await db.prepare(`SELECT p.*,c.name category_name,c.slug category_slug FROM patterns p LEFT JOIN categories c ON c.id=p.category_id WHERE ${published}${search} ORDER BY p.featured DESC,p.published_at DESC`).bind(...args).all<Row>(); return result.results.map(map); }
export async function publicPattern(slug:string) { const db=database(); if(!db)return fallbackPatterns.find((p)=>p.slug===slug); const row=await db.prepare(`SELECT p.*,c.name category_name,c.slug category_slug FROM patterns p LEFT JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND ${published}`).bind(slug).first<Row>(); return row?map(row):undefined; }
export async function publicCategories() { const db=database(); if(!db)return fallbackCategories; const result=await db.prepare(`SELECT c.*,COUNT(p.id) count FROM categories c LEFT JOIN patterns p ON p.category_id=c.id AND ${published} WHERE c.status='active' GROUP BY c.id HAVING count>0 ORDER BY c.sort_order,c.name`).all<{slug:string;name:string;description:string;count:number}>(); return result.results.map((c):Category=>({ ...c, art:art[c.slug]??"flower", size:"standard" })); }
export async function publicCategory(slug:string) { return (await publicCategories()).find((category)=>category.slug===slug); }
export async function publicPatternsByCategory(slug:string) { return (await publicPatterns()).filter((pattern)=>pattern.categorySlug===slug); }
