import type { Metadata } from "next";
import { EditorialPage } from "@/components/editorial-page";

export const metadata: Metadata = { title: "Copyright & Takedown Policy", description: "Learn how FuseMosaic handles copyright, trademark, publicity-right, and other intellectual-property concerns.", alternates: { canonical: "/copyright" } };

export default function CopyrightPage() { return <EditorialPage eyebrow="Legal" title="Copyright & Takedown Policy" copy="FuseMosaic respects the intellectual property rights of creators, artists, photographers, studios, brands, performers, publishers, and other rights holders.">
  <p><strong>Last updated: September 2026</strong></p><p>FuseMosaic is operated as an independent hobby project and currently provides its craft patterns free of charge.</p>
  <h2>Our Approach</h2><p>Many patterns on FuseMosaic are independently created designs.</p><p>Some content may also reference recognizable subjects from culture, entertainment, history, games, film, television, music, sports, or other creative works.</p><p>References to third-party names, characters, brands, personalities, trademarks, or works do not indicate ownership, sponsorship, endorsement, or authorization by the respective rights holder.</p><p>All third-party copyrights, trademarks, personality rights, publicity rights, and other intellectual property remain with their respective owners.</p>
  <h2>Reporting Intellectual Property Concerns</h2><p>If you believe that content available on FuseMosaic infringes copyright, trademark, publicity, personality, or another intellectual property right that you own or are authorized to enforce, please contact:</p><p><strong>Email: <a href="mailto:rakezhou@hotmail.com">rakezhou@hotmail.com</a></strong></p><p>To help us review the request efficiently, please include:</p><ol><li>Your name and contact information.</li><li>Identification of the rights holder you represent.</li><li>Identification of the copyrighted work, trademark, likeness, or other right at issue.</li><li>The exact FuseMosaic URL containing the material.</li><li>A brief explanation of your concern.</li><li>Information reasonably demonstrating that you are the rights holder or are authorized to act on the rights holder’s behalf.</li><li>A statement confirming that the information provided is accurate and submitted in good faith.</li></ol>
  <h2>What Happens After a Report</h2><p>When FuseMosaic receives a credible rights complaint, we will review the identified material.</p><p>Depending on the circumstances, we may temporarily disable access to the material while reviewing the request.</p><p>Where appropriate, we may voluntarily remove material without requiring the rights holder to initiate formal legal proceedings.</p><p>Our goal is to resolve legitimate intellectual-property concerns cooperatively and promptly.</p>
  <h2>Repeat or Serious Complaints</h2><p>FuseMosaic reserves the right to permanently remove content that is the subject of a substantiated rights complaint.</p><p>We may also discontinue categories of content where repeated legitimate complaints indicate that continued publication would create unnecessary intellectual-property disputes.</p>
  <h2>Misidentification</h2><p>We ask that reports identify specific URLs and specific protected material rather than making broad or unsupported removal requests.</p><p>If content appears to have been incorrectly identified, we may request additional information before making a final determination.</p>
  <h2>No Ownership Claim</h2><p>The inclusion of a third-party name, character, photograph reference, trademark, public figure, or other identifiable subject does not mean that FuseMosaic claims ownership of the underlying intellectual property.</p><p>Copyright in original pattern-design elements created specifically for FuseMosaic, where applicable, remains separate from any rights belonging to third parties.</p>
  <h2>Contact</h2><p>For intellectual-property matters and general inquiries:</p><p><strong><a href="mailto:rakezhou@hotmail.com">rakezhou@hotmail.com</a></strong></p>
</EditorialPage>; }
